# © 2025 Kaustav Ray. All rights reserved.
# Licensed under the MIT License.

name: Telegram Bot

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 * * * *"   # restart every hour

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start bot for 1 hour
        run: |
          echo "Starting bot for 1 hour..."
          python bot.py &
          BOT_PID=$!
          sleep 3600
          kill $BOT_PID || true
